name: sbrowser
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sqflite: ^2.0.2+1
  http: ^0.13.4
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  flutter_inappwebview: ^5.1.0+4
  path: ^1.8.1
  url_launcher: ^6.1.2
  flutter_downloader: ^1.8.0+1
  share: ^2.0.0
  package_info_plus: ^1.4.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
